### PR TITLE
Fix: Load checkpoint on the correct device

### LINKED ISSUE #145: Loading checkpoint with a different device [BUG]
**Describe the bug**

A checkpoint trained on the GPU does not seem to be loadable on a machine with CPU-only.

**To Reproduce**

```python
# checkpoint trained on a linux machine with GPU
from pathlib import Path
from careamics import CAREamist

careamist = CAREamist(Path("sem_n2v_1epoch.ckpt"))
```

Leads to the following error:

``` python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], [line 4](vscode-notebook-cell:?execution_count=8&line=4)
      [1](vscode-notebook-cell:?execution_count=8&line=1) from pathlib import Path
      [2](vscode-notebook-cell:?execution_count=8&line=2) from careamics import CAREamist
----> [4](vscode-notebook-cell:?execution_count=8&line=4) careamist = CAREamist(Path("sem_n2v_1epoch.ckpt"))

(...)

File ~/git/careamics/careamics/src/careamics/model_io/model_io_utils.py:67, in _load_checkpoint(path)
...
    [254](https://file+.vscode-resource.vscode-cdn.net/Users/joran.deschamps/git/careamics/careamics-examples/algorithms/n2v/~/miniconda3/envs/careamics/lib/python3.10/site-packages/torch/serialization.py:254)                        'to map your storages to the CPU.')
    [255](https://file+.vscode-resource.vscode-cdn.net/Users/joran.deschamps/git/careamics/careamics-examples/algorithms/n2v/~/miniconda3/envs/careamics/lib/python3.10/site-packages/torch/serialization.py:255) device_count = torch.cuda.device_count()
    [256](https://file+.vscode-resource.vscode-cdn.net/Users/joran.deschamps/git/careamics/careamics-examples/algorithms/n2v/~/miniconda3/envs/careamics/lib/python3.10/site-packages/torch/serialization.py:256) if device >= device_count:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Expected behavior**
Loading should be possible regardless of the device.

**Additional context**
Trained on VDI Linux with GPU, attempted loading in macOS intel.

### PR DESCRIPTION
**Pull request by jdeschamps**
### Description

Although CAREamics should be run on the GPU, users might want to use CPU to perform some tasks, such as prediction using trained network. This currently leads to issues when the model was trained on the GPU: https://github.com/CAREamics/careamics/issues/145.

This PR simply fixes that issue by detecting the current device.

- **What**: Add device parameter in `torch.load` function call.
- **Why**: Fixing https://github.com/CAREamics/careamics/issues/145 so that a CPU-only user can use a pre-trained network.

### Changes Made

- **Modified**: `model_io_utils.py`.

### Related Issues

- Fixes https://github.com/CAREamics/careamics/issues/145.

---

**Please ensure your PR meets the following requirements:**

- [x] Code builds and passes tests locally, including doctests
- [x] Pre-commit passes

### CODE REVIEW

**Comment by jdeschamps** [comment]
Requires https://github.com/CAREamics/careamics/pull/149 to be merged for tests to pass.

**Comment by melisande-c** [comment]
Is there a way to add a test for this?

**Review by CatEek — APPROVED** [review]

**Comment by jdeschamps** [comment]
> Is there a way to add a test for this?

The only thing I thought about was to have a set of models (GPU and CPU trained) and have them downloaded in the tests... I don't think this a good solution...

We could think of having our own runners at HT with the GPU and disable/enable GPU, but that's very complicated for an edge case.

**Comment by melisande-c** [comment]
> > Is there a way to add a test for this?
> 
> The only thing I thought about was to have a set of models (GPU and CPU trained) and have them downloaded in the tests... I don't think this a good solution...
> 
> We could think of having our own runners at HT with the GPU and disable/enable GPU, but that's very complicated for an edge case.

Ok I suppose if we need the runners at HT in the future, for other applications, we can add it then. For now it should stay fixed!

**Pull request merged**
