### PR TITLE
refac: made some attributes of `VAEAlgorithmConfig` optional

### PR DESCRIPTION
**Pull request by federico-carrara**
### Description

- **What**: Made all attributes, except `model`, `Optional` in `VAEAlgortihmConfig`.
- **Why**: At inference time the only the `model` attribute is needed. This allows to simplify model initialization for evaluation.
- **How**: Simply marked attributes as `Optional`, added `None` default if needed.

---

**Please ensure your PR meets the following requirements:**

- [x] Code builds and passes tests locally, including doctests
- [ ] New tests have been added (for bug fixes/features)
- [x] Pre-commit passes
- [ ] PR to the documentation exists (for bug fixes / features)

### CODE REVIEW

**Review by jdeschamps — COMMENTED** [review]
That means that we would need to check whether they have been assigned for training.

Would it make sense to simply give them a default value?

**Comment by federico-carrara** [comment]
I think I got your point, but let me be sure. The problem you are pointing out is that in this way we could instantiate an Algorithm config that will raise a RuntimrError during training since some attributes are not defined, right?

If this is the case, yeah good point. I guess a solution is to change the default values of the pydantic configs, e.g.,
```
loss: Optional[LVAELossConfig] = LVAELossConfig()
```

What do you think?

**Comment by federico-carrara** [comment]
Or we could also skip this PR. However, it is really ugly to load a loss config or an optimizer config which are just useless at inference time...

**Comment by jdeschamps** [comment]
Sorry I lost track of this. 

I do prefer having an unused parameter class than guarding against it being `None` in the training calls.

**Comment by federico-carrara** [comment]
I completely see your point. Let's skip this PR then, not important at all!
If you agree I will close it :)

**Pull request closed without merging**
