### PR TITLE
Fix some pre-commit errors

### PR DESCRIPTION
**Pull request by jdeschamps**
### Description

Fix ruff and some mypy errors.

Notes:
- `NDFlip` has been renamed `XYFlip` since it is not flipping z since an earlier PR

---

**Please ensure your PR meets the following requirements:**

- [x] Code builds and passes tests locally, including doctests
- [x] New tests have been added (for bug fixes/features)
- [ ] Pre-commit passes
- [x] PR to the documentation exists (for bug fixes / features)

### CODE REVIEW

**Comment by jdeschamps** [comment]
Once this PR and https://github.com/CAREamics/careamics/pull/124 are merged, we should be down to just a handful of docstring and mypy errors which will be the subject of a different PR as they relate to different refactoring.

**Review by melisande-c — APPROVED** [review]
Nice!

**Comment by CatEek** [comment]
supported_extraction_strategies.py was removed, why? Sorry if i'm missing something

**Comment by jdeschamps** [comment]
> supported_extraction_strategies.py was removed, why? Sorry if i'm missing something

It was unused!

**Pull request merged**
